apiVersion: apps/v1
kind: Deployment
metadata:
  name: roshambo-backend
  labels:
    app: roshambo-backend
    app.openshift.io/runtime: quarkus
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: roshambo-backend
  template:
    metadata:
      labels:
        app: roshambo-backend
    spec:
      containers:
        - name: roshambo-backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: {{ .Values.backend.resources | toYaml | nindent 12 }}
