apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rps-game
spec:
  project: default
  source:
    repoURL: 'https://github.com/redhat-developer-demos/rps-game'
    path: helm
    targetRevision: k8s-resources
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rps-game
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true